<a href="https://colab.research.google.com/github/NishmithaJR/Data-Analytics/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing Libraries
import numpy as np
import pandas as pd
import warnings
warnings. filterwarnings('ignore')

In [ ]:
#importing Dataset
df= pd.read_csv('train.csv')
df. head (5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df. describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
#Name column can never decide survival of a person, hence we can delete it.
df [ "Name"]
df .head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
del df[ "Ticket"]
df. head ()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,NaN,S

In [ ]:
del df[ 'Fare']
df. head

<bound method NDFrame.head of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch Cabin Embarked
0        0   NaN        S
1        0   C85        C
2        0   NaN        S
3        0  C123        S
4        0   NaN        S
..     ...   ...      ...
886      0   NaN        S
887      0   B42        S
888      2   NaN        S
889      0  C148        C
890      0   NaN        Q

[891 rows x 10 columns]>

In [ ]:
del df[ 'Cabin']
df. head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,S

In [ ]:
def getNumber (str) :
 if str=="male":
  return 1
 else:
  return 2
df ["Gender"] = df['Sex'].apply(getNumber)
#we have created a new column called "Gender" and #filling it with values 1,2 based on the values of sex column df.head()

In [ ]:
#Deleting Sex column, since no use of it now
del df["Sex"]
df.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Embarked,Gender
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,C,2
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,S,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,S,2
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,S,1

In [ ]:
df.isnull()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Embarked,Gender
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False
887,False,False,False,False,False,False,False,False,False
888,False,False,False,False,True,False,False,False,False
889,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Age            177
SibSp            0
Parch            0
Embarked         2
Gender           0
dtype: int64

In [ ]:
means = df[df.Survived==1].Age.mean()
means

np.float64(28.343689655172415)

In [ ]:
df["age"]=np. where(pd.isnull(df.Age) & df["Survived"]==1 ,means, df["Age"])
df. head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Embarked,Gender,age
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,S,1,22.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,C,2,38.0
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,S,2,26.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,S,2,35.0
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,S,1,35.0

In [ ]:
df["age"]=np. where(pd.isnull(df.Age) & df["Survived"]==1 ,means, df["Age"])
df. head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Embarked,Gender,age
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,S,1,22.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,C,2,38.0
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,S,2,26.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,S,2,35.0
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,S,1,35.0

In [ ]:
# Finding the mean age of "Not Survived" people
meanNS=df[df.Survived==0].Age.mean()
meanNS

np.float64(30.62617924528302)

In [ ]:
df.age.fillna(meanNS, inplace=True)
df. head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Embarked,Gender,age
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,S,1,22.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,C,2,38.0
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,S,2,26.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,S,2,35.0
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,S,1,35.0

In [ ]:
df. isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Age            177
SibSp            0
Parch            0
Embarked         2
Gender           0
age              0
dtype: int64

In [ ]:
del df[ 'Age']
df. head

<bound method NDFrame.head of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name  SibSp  Parch Embarked  \
0                              Braund, Mr. Owen Harris      1      0        S
1    Cumings, Mrs. John Bradley (Florence Briggs Th...      1      0        C
2                               Heikkinen, Miss. Laina      0      0        S
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)      1      0        S
4                             Allen, Mr. William Henry      0      0        S
..                                                 ...    ...    ...      ...
886                              Montvila, Rev. Juozas      0      0        S
887                       Graham, Miss. Margaret Edith      0      0        S
888           Johnston, Miss. Catherine Helen "Carrie"      1      2        S
889                              Behr, Mr. Karl Howell      0      0        C
890                                Dooley, Mr. Patrick      0      0        Q

     Gender        age
0         1  22.000000
1         2  38.000000
2         2  26.000000
3         2  35.000000
4         1  35.000000
..      ...        ...
886       1  27.000000
887       2  19.000000
888       2  30.626179
889       1  26.000000
890       1  32.000000

[891 rows x 9 columns]>

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
SibSp          0
Parch          0
Embarked       2
Gender         0
age            0
dtype: int64

In [ ]:
pd. isnull(df).sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
SibSp          0
Parch          0
Embarked       2
Gender         0
age            0
dtype: int64

In [ ]:
# Finding the number of people who have survived
# given that they have embarked or boarded from a particular port
survivedQ = df [df. Embarked == 'Q'][df.Survived == 1].shape[0]
survivedC = df [df.Embarked == 'C'][df. Survived == 1].shape[0]
survivedS = df [df. Embarked == 'S'][df. Survived == 1].shape[0]
print(survivedQ)
print (survivedC)
print(survivedS)

30
93
217

In [ ]:
survivedQ = df[df. Embarked == 'Q'][df. Survived == 0].shape[0]
survivedC = df [df. Embarked == 'C'][df.Survived == 0].shape[0]
survivedS= df[df. Embarked == 'S'][df. Survived == 0].shape[0]
print(survivedQ)
print (survivedC)
print(survivedS)

47
75
427

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
SibSp          0
Parch          0
Embarked       2
Gender         0
age            0
dtype: int64

In [ ]:
df.dropna (inplace=True)
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
SibSp          0
Parch          0
Embarked       0
Gender         0
age            0
dtype: int64

In [ ]:
#Renaming "age" and "gender" columns
df.rename(columns={'age': 'Age'}, inplace=True)
df.head()

,PassengerId,Survived,Pclass,Name,SibSp,Parch,Embarked,Gender,Age
0,1,0,3,"Braund, Mr. Owen Harris",1,0,S,1,22.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,0,C,2,38.0
2,3,1,3,"Heikkinen, Miss. Laina",0,0,S,2,26.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,0,S,2,35.0
4,5,0,3,"Allen, Mr. William Henry",0,0,S,1,35.0

In [ ]:
df.rename(columns={'Gender': 'Sex'}, inplace=True)
df.head()

,PassengerId,Survived,Pclass,Name,SibSp,Parch,Embarked,Sex,Age
0,1,0,3,"Braund, Mr. Owen Harris",1,0,S,1,22.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,0,C,2,38.0
2,3,1,3,"Heikkinen, Miss. Laina",0,0,S,2,26.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,0,S,2,35.0
4,5,0,3,"Allen, Mr. William Henry",0,0,S,1,35.0

In [ ]:
#Changing the categorical value of 'Embarked' attribute to numerical value, S-1, Q-2,
def getEmbark (str):
 if str=="S":
  return 1
 elif str=="Q":
  return 2
 else:
  return 3
df["Embark"]=df["Embarked"].apply(getEmbark)
df.head()

,PassengerId,Survived,Pclass,Name,SibSp,Parch,Embarked,Sex,Age,Embark
0,1,0,3,"Braund, Mr. Owen Harris",1,0,S,1,22.0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,0,C,2,38.0,3
2,3,1,3,"Heikkinen, Miss. Laina",0,0,S,2,26.0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,0,S,2,35.0,1
4,5,0,3,"Allen, Mr. William Henry",0,0,S,1,35.0,1

In [ ]:
del df['Embarked']
df.rename(columns= { 'Embark': 'Embarked'}, inplace=True)
df.head()

,PassengerId,Survived,Pclass,Name,SibSp,Parch,Sex,Age,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,0,1,22.0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,0,2,38.0,3
2,3,1,3,"Heikkinen, Miss. Laina",0,0,2,26.0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,0,2,35.0,1
4,5,0,3,"Allen, Mr. William Henry",0,0,1,35.0,1

In [ ]:
#Drawing a pie chart for number of males and females aboard
import matplotlib.pyplot as plt
from matplotlib import style
males = (df[ 'Sex'] == 1).sum()
#Summing up all the values of column gender with a
#condition for male and similary for females
females = (df[ 'Sex'] == 2).sum()
print(males)
print (females)
p = [males, females]
plt.pie(p, #giving array
labels = ['Male', 'Female'], #Correspndingly giving Labels colors = ['green', 'yellow'],
explode = (0.15, 0),
# Corresponding colors
#How much the gap should me there between the pies startangle = 0) #what start angle should be given
plt.axis('equal')
plt.show()

In [ ]:
# More Precise Pie Chart
MaleS=df[df.Sex==1][df. Survived ==1].shape[0] print (Males)
MaleN=df[df. Sex==1][df. Survived==0].shape[0] print (MaleN)
FemaleS=df[df.Sex==2][df. Survived ==1].shape[0] print (Females)
FemaleN=df[df.Sex==2][df. Survived ==0].shape[0]
print(FemaleN)

In [ ]:
chart=[Males, MaleN, Females, FemaleN]
colors=['lightskyblue', 'yellowgreen', 'Yellow', 'Orange']
labels=["Survived Male", "Not Survived Male", "Survived Female", "Not Survived Female"] explode=[0,0.05,0,0.1]
plt.pie(chart, labels=labels, colors=colors, explode=explode, startangle=100, counterclock=Fa plt.axis("equal")
plt.show()